title: Dave Thompson
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.1875
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#ae7200'
    - '#120e10'
    - '#603f0c'
    - '#352b0d'
    - '#da9c3c'
  lightness: 0.625
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: davethompson.ca
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.01664876
layout_spectrum: 0.9833512
