layout_spectrum: 0.5702535873278975
typography_spectrum: 0.658091729041189
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.3583054607734084
  lightness: 0.17906716489233077
  saturation: 0.5844478514045477
  rhythmicContrast: 0.5410157155711204
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Dave Thompson
name: Dave Thompson
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Biography
    id: 98a168c8-140b-4c4e-b14e-cf2a54249e16
    type: content
  - name: Facebook
    url: 'http://www.facebook.com/davethompson.ca/'
    type: external
  - name: Twitter
    url: 'http://twitter.com/davethompson'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Dave Thompson
description: writer.player.maker
purpose: []
