typography_spectrum: 0.7406015
color:
  brandColors:
    - '#ae7200'
    - '#120e10'
    - '#603f0c'
    - '#352b0d'
    - '#da9c3c'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2367
analytics:
  google: null
  facebook: null
  twitter: null
name: Dave Thompson
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Facebook
    url: 'http://www.facebook.com/davethompson.ca/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Dave Thompson
description: writer.player.maker
purpose: []
