name: davethompson.ca
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39365
title: Dave Thompson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ae7200'
    - '#120e10'
    - '#603f0c'
    - '#352b0d'
    - '#da9c3c'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
