name: davethompson.ca
favicon: null
layout_spectrum: 0.9833512
typography_spectrum: 0.6074114
title: Dave Thompson
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ae7200'
    - '#120e10'
    - '#603f0c'
    - '#352b0d'
    - '#da9c3c'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
